import type { Boss } from './theme';

/**
 * HUNTER×HUNTER テーマのボス（Ver1 の src/constants/bossConfigs.ts から取った名前・台詞）。
 * 出題は、Ver1 の各章の最後のステージ（総合チャレンジ）の語彙（pack）。読み込めないときは packId の組み込みパックで代替する。
 * お題の数・ミスの許容は、Ver1 の難易度（maxMisses）に合わせた。
 * 画像は Ver1 に実物があった 1・2 章だけ（他の章は Ver1 でも仮の画像だったので、使わない）。
 */
export const HUNTER_BOSSES: Boss[] = [
  {
    id: 'chapter1',
    chapter: 1,
    name: 'ヒソカ',
    title: '奇術師',
    description: '危険な奇術師。戦いを楽しむ狂戦士。',
    image: 'themes/hunter/bosses/chapter1.png',
    packId: 'basic',
    pack: 'themes/hunter/stages/c1s6.json',
    words: 10,
    maxMisses: 5,
    skill: { kind: 'hide', name: 'トランプの奇術', text: '3 つに 1 つのお題で、ローマ字ガイドの残りが隠れます（読みと表示は見えます）' },
    intro: '♠ さぁ...殺し合おうか ♣',
    dialogues: ['♠ さあ、遊ぼうか ♣', '♥ まだまだだね ♦', '♠ いい緊張感だ ♣', '♥ なかなかやるじゃないか ♦'],
    phaseMessages: ['♥ ようやく本気を出す気になったよ ♦', '♠ さすがだ...でもまだ足りない ♣', '♥ これが最後の一手だ ♦'],
    defeat: '♠ 楽しかったよ...また遊ぼう ♣',
  },
  {
    id: 'chapter2',
    chapter: 2,
    name: 'サダソ・リールベルト・ギド',
    title: '天空闘技場の刺客',
    description: '天空闘技場でゴンとキルアを狙う3人組の念能力者。',
    image: 'themes/hunter/bosses/chapter2.png',
    packId: 'basic',
    pack: 'themes/hunter/stages/c2s6.json',
    words: 15,
    maxMisses: 3,
    attacks: { everyWords: 3, windowSec: 8 }, // 値は仮（実機で調整）
    intro: 'お前たちを始末してやる！',
    dialogues: ['お前たちを倒せば200階に行ける', '舐めるな小僧！', '俺たちの連携を見せてやる', 'この勝負、もらった！'],
    phaseMessages: ['連携を強化するぞ！', 'もう手加減はしない！', '最終手段だ...覚悟しろ！'],
    defeat: 'バカな...こんな小僧に...',
  },
  {
    id: 'chapter3',
    chapter: 3,
    name: 'クロロ',
    title: '幻影旅団団長',
    description: '幻影旅団の指導者。冷徹で戦略的。',
    packId: 'english',
    pack: 'themes/hunter/stages/c3s6.json',
    words: 12,
    maxMisses: 2,
    skill: { kind: 'strip', name: 'スキルハンター', text: '直前のお題でミスをすると、次のお題は運指ガイドを奪われます' },
    intro: '盗賊の美学を見せてやろう',
    dialogues: ['盗賊団の本領を見せよう', 'つまらん', '速度が落ちているようだ', 'まだやるのか'],
    phaseMessages: ['盗賊の秘技（スキルハンター）を発動する', '面白い...本気で相手をしよう', 'これが最終形態だ...覚悟しろ'],
    defeat: 'お前は...強いな',
  },
  {
    id: 'chapter4',
    chapter: 4,
    name: 'ビスケ',
    title: '格闘技の達人',
    description: 'G・I島での修行者。強力な念能力者。',
    packId: 'symbols',
    pack: 'themes/hunter/stages/c4s6.json',
    words: 12,
    maxMisses: 5,
    skill: { kind: 'stamina', name: 'スタミナ', text: '正しい打鍵が 10 連続するごとに、ミスを 1 回ぶん回復します（ランクはミスの総数で決まります）' },
    intro: '修行の時間よ！ついてきなさい！',
    dialogues: ['いい修行になるな', 'もっと本気を出せ', '体力が続くか', '認めてやろう'],
    phaseMessages: ['やるじゃない...本気を出すわよ', 'これが真の力よ！', '最終試練...耐えてみなさい！'],
    defeat: '合格よ！よくやったわ！',
  },
  {
    id: 'chapter5',
    chapter: 5,
    name: '老ビスケ',
    title: '究極の修行者',
    description: '若き日のビスケの姿。最強の念能力者。',
    packId: 'phrases',
    pack: 'themes/hunter/stages/c5s6.json',
    words: 8,
    maxMisses: 3,
    timeLimitSec: 75,
    attacks: { everyWords: 4, windowSec: 15 }, // 値は仮。長文の語なので猶予を長く
    intro: '真の修行を教えてやる',
    dialogues: ['本当の修行が始まる', '甘い', '形態を変える', '究極の力を見せる'],
    phaseMessages: ['形態を変えるぞ...ついてこい', '究極の念を見せてやろう', '限界突破...これが本当の力だ！'],
    defeat: '認めてやろう...お前は強い',
  },
  {
    id: 'chapter6',
    chapter: 6,
    name: 'メルエム',
    title: 'キメラアント王',
    description: 'キメラアントの完全な王。最強の存在。',
    packId: 'phrases',
    pack: 'themes/hunter/stages/c6s6.json',
    words: 12,
    maxMisses: 1,
    timeLimitSec: 90,
    intro: '王の前にひざまずけ',
    dialogues: ['王の力を感じよ', '人間ごときが', '興味深い', '究極を超える力'],
    phaseMessages: ['興味深い...少しだけ本気を出そう', '人間ごときが...ここまでやるとはな', '究極の力を見せてやろう...これが王だ'],
    defeat: 'まさか...人間に敗れるとは...',
  },
  {
    id: 'chapter7',
    chapter: 7,
    name: 'ネテロ会長',
    title: '究極の試練',
    description: 'ハンター協会会長。全ての修行の集大成。',
    packId: 'phrases',
    pack: 'themes/hunter/stages/c7s6.json',
    words: 15,
    maxMisses: 2,
    timeLimitSec: 120,
    intro: '百式観音の力を見せよう',
    dialogues: ['ハンターの道の果てを見せよう', 'その程度か', '制約と誓いの究極', 'よくやったな'],
    phaseMessages: ['感謝の正拳突き...一万回の祈りを込めて', '零の手...これが最後の切り札だ', '究極の試練...全てを出し尽くせ'],
    defeat: 'よくぞここまで...お見事だ',
  },
];
